### ISSUE TITLE
When command is sent to chat, exception occurs.

### ISSUE THREAD

**Issue by MattMadness** [Half-Shot/matrix-mpd-dj#9]
I have the bot running with python3 (should it be python2? trying to get that set up but it's a pain) and when I send a command to the bot this exception occurs:

```
Exception thrown during sync
Traceback (most recent call last):
  File "/var/lib/mpd/matrix-mpd-dj/python/matrix_client/client.py", line 490, in listen_forever
    self._sync(timeout_ms)
  File "/var/lib/mpd/matrix-mpd-dj/python/matrix_client/client.py", line 624, in _sync
    room._put_event(event)
  File "/var/lib/mpd/matrix-mpd-dj/python/matrix_client/room.py", line 311, in _put_event
    listener['callback'](self, event)
TypeError: __on_cmd() takes 2 positional arguments but 3 were given
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/mpd/matrix-mpd-dj/python/matrix_client/client.py", line 490, in listen_forever
    self._sync(timeout_ms)
  File "/var/lib/mpd/matrix-mpd-dj/python/matrix_client/client.py", line 624, in _sync
    room._put_event(event)
  File "/var/lib/mpd/matrix-mpd-dj/python/matrix_client/room.py", line 311, in _put_event
    listener['callback'](self, event)
TypeError: __on_cmd() takes 2 positional arguments but 3 were given
```

The command then, does not work.

**Comment by srayneau** [comment]
Same error here !
